#开发环境配置
server:
  #服务端口
  port: 8000
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    # 开启gzip 压缩返回数据
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    port-header: X-Forwarded-Port
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
#自定义资源目录
spring.mvc.static-path-pattern: /**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/ajjyy02/shms/file/
#日志配置
logging:
  level:
    com.jd: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
#Spring配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    # 禁用缓存
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  #文件上传
  servlet:
     multipart:
       max-file-size:  10MB
       max-request-size:  10MB
  devtools:
    restart:
      #热部署开关
      enabled: true
  activiti:
    check-process-definitions: false
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.jd
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
# 代码生成
gen: 
  # 作者
  author: TrevorPhilips
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.jd.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_

# 项目相关配置
project:
  #名称
  name: jd
  #版本
  version: 0.1
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: false
  # 企业定级不符合项数量
  minNum: 10
  maxNum: 30
  #企业角色ID
  companyRoleId: 3
  #街道角色ID
  streetRoleId: 10
dict:
  #企业基础信息有关的字典key
  qyjcxxDict:
    #大中小微
    - enterprise_scale
    #上级公司
    - superior_company
    #专门安全机构
    - specialized_safety_agencies
    #专职安全人员
    - fulltime_security_personnel
    #重大危险源
    - major_hazards
    #规模情况
    - scale_situation
    #企业经营状态
    - enterprise_operation_state
    #行业表类型
    - industry_code
    #营业执照类型
    - business_license_type
    #企业经营状态
    - enterprise_operation_state
upLoadDir: /home/ajjyy02/shms/file/

spring.devtools.restart.trigger-file: trigger.txt

ls:

  lsUrl: http://58.213.148.39:9090/jnaj/services/webservice?wsdl
  #查询所有用户信息
  queryYhxxList: queryYhxxWebServiceDataSet
  #根据用户名查询用户信息
  queryYhxxByUsername: queryYhxxByUsername
  #查询所有组织信息
  queryZzjgxxList: queryZzjgxxWebServiceDataSet
  #获取角色信息
  queryJsxxList: queryJsxxList
  #角色用户关联
  queryUserRoleList: queryUserRoleList
  #app访问地址
  appUrl: http://58.213.148.39:9090/
  
scheduled:
  #每天凌晨一点执行 --  0 0 1 * * ?
  cron: 0 38 11 * * ?
  
zabbix:
  url: http://192.168.1.106:8080/zabbix/api_jsonrpc.php
  userName: Admin
  password: zabbix
  physicalServer: 物理服务器群组